name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/movie-service-image

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Build jar bằng Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4️⃣ Login DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name : Remove container
        run: |
          docker rmi movie-service:latest || true

      # 5️⃣ Build & push Docker image
      - name: Build & push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          FULL_IMAGE="${IMAGE_NAME}:${GITHUB_SHA}"
          echo "full_image=$FULL_IMAGE" >> $GITHUB_OUTPUT
          
          docker build --no-cache --file Dockerfile \
            --tag "$FULL_IMAGE" \
            --tag "${IMAGE_NAME}:latest" \
            .

          docker push "$FULL_IMAGE"
          docker push "${IMAGE_NAME}:latest"